ALTER TABLE employers
MODIFY COLUMN is_hiring BOOLEAN DEFAULT FALSE;

ALTER TABLE conversations
MODIFY COLUMN date_sent TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
MODIFY COLUMN full_name VARCHAR(300);

ALTER TABLE users
MODIFY COLUMN full_name VARCHAR(300) NOT NULL,
  MODIFY COLUMN current_status ENUM('employed', 'self-employed', 'unemployed') NOT NULL;

DESCRIBE users;